[DEFAULT]
col_delimiter = |++|

[XDR_PATH]
xdr_template_file =  xdr_check_template-IOT.xlsx
#移动僵木儒
host_controlled_.csv-fncheck = /home/data/log_bak/jmr_host_controlled
network_attacks_.csv-fncheck = /home/data/log_bak/jmr_network_attacks
unwanted_programs_.csv-fncheck = /home/data/log_bak/spread_unwanted_programs
app_sample_.csv-fncheck = /home/data/log_bak/jmr_app_sample
suspected_sample_.csv-fncheck = /home/data/log_bak/jmr_suspected_sample
malware_resource_.csv-fncheck = /home/data/log_bak/jmr_malware_resource
malware_pkt_.csv-fncheck = /home/data/log_bak/jmr_malware_pkt
malware_file_.csv-fncheck = /home/data/log_bak/jmr_malware_file
jmr_rpc_.csv-fncheck = /home/data/log_bak/jmr_rpc
jmr_gbt32960_.csv-fncheck = /home/data/log_bak/jmr_gbt32960
jmr_jt808_.csv-fncheck = /home/data/log_bak/jmr_jt808
jmr_jtt905_.csv-fncheck = /home/data/log_bak/jmr_jtt905
jmr_iovtltj_.csv-fncheck = /home/data/log_bak/jmr_iovtltj
jmr_plaintext_trans.csv-fncheck = /home/data/log_bak/jmr_plaintext_trans
